[package]
name = "pgsteward-integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
pgsteward-core.workspace = true
pgsteward-harness = { workspace = true, features = ["postgres"] }
anyhow.workspace = true
testcontainers.workspace = true
testcontainers-modules.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true

[lints]
workspace = true
