[package]
name = "pgsteward-harness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []
postgres = ["dep:tokio-postgres"]

[dependencies]
pgsteward-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres = { workspace = true, optional = true }
tracing.workspace = true

[lints]
workspace = true
